name: CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'tests/**'
      - '**/*_test.py'
      - 'app.py'
  pull_request:
    branches: [main]
    paths:
      - 'tests/**'
      - '**/*_test.py'
      - 'app.py'

jobs:
  run-tests-and-sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flask selenium openpyxl

      - name: Iniciar servidor Flask en background
        run: |
          export FLASK_APP=app.py
          nohup flask run --host=127.0.0.1 --port=5000 &

      - name: Esperar a que el servidor Flask arranque
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:5000/form.html && break
            sleep 1
          done

      - name: Ejecutar pruebas Selenium
        run: |
          python tests/test_selenium.py

      - name: Ejecutar pruebas pytest con cobertura
        run: |
          mkdir -p reports
          pytest --cov=validators --cov-report=xml

      - name: Descargar e instalar SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip

      - name: Ejecutar análisis SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
            -Dsonar.organization=hunter987 \
            -Dsonar.projectKey=hunter987_GIT-REGISTRY-FORM \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.sources=.